#!/bin/bash
#-----------------------
# Testing utilities help
#-----------------------
set -e

# Not working
#  swift-account-audit
#  swift-drive-audit
#  swift-form-signature
#  swift-recon-cron
#  swift-ring-builder
#  swift-temp-url

HELP_CMD=(
 'swift-account-auditor' 'swift-account-info' 'swift-account-reaper'
 'swift-account-replicator' 'swift-account-server' 'swift-config'
 'swift-container-auditor' 'swift-container-info' 'swift-container-reconciler'
 'swift-container-replicator' 'swift-container-server' 'swift-container-sync'
 'swift-container-updater' 'swift-dispersion-populate'
 'swift-dispersion-report' 'swift-get-nodes' 'swift-init'
 'swift-object-auditor' 'swift-object-expirer' 'swift-object-info'
 'swift-object-reconstructor' 'swift-object-replicator' 'swift-object-server'
 'swift-object-updater' 'swift-oldies' 'swift-orphans' 'swift-proxy-server'
 'swift-recon' 'swift-reconciler-enqueue' 'swift-ring-builder-analyzer'
)
for client in "${HELP_CMD[@]}"; do
    if ! $client -h 2>&1 > /dev/null; then
        echo "ERROR, ${client} is not running"
        exit 1
    else
        echo "OK: ${client} is running"
    fi
done
exit 0
