.TH swift-init 8
.SH NAME
swift\-init \- Please fill

.SH SYNOPSIS
.B swift-init
.B server-name
.B ACTION

.SH DESCRIPTION
.B swift-init

This Python script is responsible for starting and stopping the different daemons of swift.

.SH PARAMETERS

.LP
.B server-name
.IP

This parameter is the name of the swift service you wish to have an action on.

.LP
.B ACTION
.IP

This parameter can be one of these: start stop shutdown restart reload once.
