#!/bin/sh

set -e

if [ "$1" = "upgrade" ] ; then
    # If downgrading to version older than 2.6.0-2 stop service first. In this
    # version init scripts was rewritten and swift-init support was dropped
    if dpkg --compare-versions "$2" lt "2.6.0-2" ; then
        echo "Downgrading to < 2.6.0-2, need to stop service first"

        invoke-rc.d swift-proxy stop || true
    fi
fi

#DEBHELPER#

exit 0
